version: '3.5'

services:
  passive-dns-api:
    image: passive-dns-api
    container_name: passive-dns-api
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    network_mode: "host"
    command: ./api_server/passive-dns-api